# Generated by Django 4.1.2 on 2022-11-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pji3g54app', '0002_cadastro_inputcpf_cadastro_inputnome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='inputCPF',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
